image:
  - Visual Studio 2022
stack: go 1.18.2

for:
-
  matrix:
    only:
      - image: macOS

  environment:
    GOPATH: /tmp/
  clone_folder: /tmp/go/src/github.com/travertexs/overture
  before_build:
    - "echo Building from macOS"
    - "go env"
    - "ls -al"
    - "python3 ./build.py -create-sample"
    - "python3 ./build.py -build-ios"

-
  matrix:
    only:
      - image: Ubuntu
  
  init:
  environment:
    APPVEYOR_SSH_KEY: ""
    GOPATH: /usr/go/
    ANDROID_NDK_ROOT: /tmp/android-ndk-r16b
  clone_folder: /usr/go/src/github.com/travertexs/overture
  before_build:
    - "wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O /tmp/android-ndk.zip"
    - "unzip -q /tmp/android-ndk.zip -d /tmp"
    - "python $ANDROID_NDK_ROOT/build/tools/make_standalone_toolchain.py --api=16 --install-dir=$ANDROID_NDK_ROOT/bin/arm-linux-androideabi/ --arch=arm"
    - "python $ANDROID_NDK_ROOT/build/tools/make_standalone_toolchain.py --api=21 --install-dir=$ANDROID_NDK_ROOT/bin/aarch64-linux-android/ --arch=arm64"
    - "python $ANDROID_NDK_ROOT/build/tools/make_standalone_toolchain.py --api=16 --install-dir=$ANDROID_NDK_ROOT/bin/i686-linux-android/ --arch=x86"
    - "python $ANDROID_NDK_ROOT/build/tools/make_standalone_toolchain.py --api=21 --install-dir=$ANDROID_NDK_ROOT/bin/x86_64-linux-android/ --arch=x86_64"
    - "python3 ./build.py -create-sample"
    - "python3 ./build.py -build-android"
    - "python3 ./build.py -build"
  on_finish:
    - "go test -cover ./... -race -coverprofile=coverage.txt -covermode=atomic"
    - "bash <(curl -s https://codecov.io/bash)"

branches:
  only:
    - master

artifacts:
  - path: 'overture-*.zip'

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: bkFCV3S/fgcuuZevFwUJicGIhL1s5aUM8ML2Tc1IHL9/CTWY5hi//KBqM+83knPM
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only